# Documentation: https://docs.github.com/en/code-security/how-tos/secure-your-supply-chain/secure-your-dependencies/configure-version-updates

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
